class CSVModel:
    KEY_NODE = 'e'
    KEY_RELATION = 'r'
    INDEX_NODE_ID = 1
    INDEX_NODE_NAME = 2
    INDEX_NODE_TYPE = 3
    INDEX_NODE_WEIGHT = 4
    INDEX_NODE_FORMATTED_NAME = 5
    NODE_TYPE_TERM = 1
    INDEX_RELATION_NODE1 = 2
    INDEX_RELATION_NODE2 = 3
    INDEX_RELATION_TYPE = 4
    RELATION_TYPE_DOMAIN = 3
    RELATION_TYPE_ASSOCIATION = 0
    RELATION_TYPE_HAS_PART = 9

